## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_module('topology', ['node'])
    obj.source = [
	'model/topology.cc',
	'helper/cube.cc',
	'helper/torus.cc',
	'helper/tree.cc',
	'helper/mesh.cc'
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'topology'
    headers.source = [
	'model/topology.h',
	'helper/cube.h',
	'helper/torus.h',
	'helper/tree.h',
	'helper/mesh.h'
        ]

